# AppVeyor config for https://github.com/inflatablefriends/lastfm

configuration: Release

install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.5.0/nuget.exe

before_build:
  - ps: nuget restore IF.Lastfm.sln

build:
  project: IF.Lastfm.sln

test_script:
  - ps: .\run-tests.ps1

image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

notifications:
  - provider: Webhook # ping Gitter ticker 
    url: https://webhooks.gitter.im/e/aa615fb57d382a430815

#---------------------------------------------------------------

for:
  -
    branches:
      only:
        - master
        - /v.*/

    version: 1.1.999.{build}
    
    after_test:
      - ps: pushd .nuget
      - ps: .\pack.ps1 -versionSuffix prerelease
      - ps: popd
      - ps: cp .\.nuget\*.nupkg . 

    artifacts:
      - path: src\IF.Lastfm.Core\bin\Release\netstandard1.1\IF.Lastfm.Core.dll
        name: IF.Lastfm.Core.dll
      - path: src\IF.Lastfm.SQLite\bin\Release\netstandard1.1\IF.Lastfm.SQLite.dll
        name: IF.Lastfm.SQLite.dll
      - path: '\*-prerelease.nupkg'

  -
    branches:
      only:
        - release

    # don't forget to update this!
    version: 1.1.0.{build}
    
    after_test:
      - ps: pushd .nuget
      - ps: .\pack.ps1
      - ps: popd
      - ps: cp .\.nuget\*.nupkg . 

    artifacts:
      - path: src\IF.Lastfm.Core\bin\Release\netstandard1.1\IF.Lastfm.Core.dll
        name: IF.Lastfm.Core.dll
      - path: src\IF.Lastfm.SQLite\bin\Release\netstandard1.1\IF.Lastfm.SQLite.dll
        name: IF.Lastfm.SQLite.dll
      - path: '\*.nupkg'

    deploy:
      provider: NuGet
      api_key:
        secure: va1LSoMMALhdweWJ7jzaarnm/nSD5Y+6g39YVSsjc9tfMljmqSj3LX366ysaTcau
      artifact: /.*\.nupkg/
